### ISSUE TITLE
Support LocalAI

### ISSUE THREAD

**Issue by dxcore35** [HyeonseoNam/auto-classifier#15]
Please, please!!!

Support LocalAI https://www.youtube.com/watch?v=3yPVDI8wZcI
It is already implemented in the plugin https://github.com/logancyang/obsidian-copilot

I don't think it will be too much code to copy relevant code from this project and implement fully local AI. 

Thank you very much for your work!

**Comment by creuzerm** [comment]
This could be as simple as allowing us to change the URL for the ChatGPT endpoint as some of our local libraries now are chatGPT API compatible.

**Comment by AndyDavis8** [comment]
It would be great if this project support local AI such as Ollama, LM Studio...

**Comment by HyeonseoNam** [comment]
Hi @dxcore35, @creuzerm , @AndyDavis8 ,
(thanks to @rtuszik), you can now use the OpenAI-compatible LLM API (possibly enabling it for Ollama) on version 1.2.0.
Consider updating the base URL to point to the address that calls your local LLM.

**Comment by rtuszik** [comment]
> Not working!
> 
> 
> 
> ![Screenshot 2024-12-12 at 16 41 56](https://github.com/user-attachments/assets/96d2ecf7-2def-4ed0-9189-cdbf50847873)
> 
> 
> 
> ![Screenshot 2024-12-12 at 16 42 12](https://github.com/user-attachments/assets/4b070d69-f9fe-4350-8406-aee179fc41b6)
> 
> 
> 
> There is no API key for Ollama.
> 
> 

I opened #30 for this. Will look into it.

**Comment by rtuszik** [comment]
@dxcore35 
You can just use any random input for the API key. You need to use the following baseurl: http://localhost:11434/v1

**Comment by dxcore35** [comment]
✅ The base url set
✅ Random api
✅ Connection to Ollama works
🛑 After pressing classify content:

![Screenshot 2024-12-12 at 20 11 13](https://github.com/user-attachments/assets/61419162-efcc-49c6-8960-2b7ef32e5d2c)

**Comment by rtuszik** [comment]
From what I can see, The issue here is that the models don't adhere to the format. 
Using ollama3.2, I have gotten these sort of responses:

`"content": "JSON {\n  \"reliability\": 0.9,\n  \"outputs\": [\n    \"nato\",\n    \"treaty\",\n    \"international-law\",\n    \"war\",\n    \"military\",\n    \"politics\"\n  ]\n}"`

where it just prefaces the JSON with `JSON`. 


`"content": "JSON output:\n{\n  \"reliability\": 0.9,\n  \"outputs\": [\n    \"international-law\",\n    \"treaty\",\n    \"nato\",\n    \"united-nations\"\n  ]\n}\n\nNote: The reliability score is 0.9 because the content appears to be a North Atlantic Treaty Organization (NATO) treaty, which is an international organization and a type of treaty. The other options are not directly related to the content."`

where it appends text to the JSON. 

Its impossible to account for that lack of prompt adherence. I am not sure if the format parameter works with the OpenAI-node library.

For now I can only recommend to try using different models to see if one will do. Feel free to also send some debug information about the completions you received.

**Comment by dxcore35** [comment]
I think he need to implement this for Ollama:

https://github.com/abetlen/llama-cpp-python?tab=readme-ov-file#json-schema-mode

**Comment by dxcore35** [comment]
They implement the structure output few days back!
https://ollama.com/blog/structured-outputs

It will force any model to adhere to JSON

**Comment by rtuszik** [comment]
@dxcore35 
it best to edit your comments instead of re-commenting after such short time. I would ask you to follow #31 for updates on this, as this issue is closed. 

The `format` parameter I had mentioned is what you suggest with the structured outputs. 

I will be looking into this, though this might require some significant work and possible an alternative to OpenAI-node.

**Comment by creuzerm** [comment]
Thank you. I can confirm that this works with a remote server, custom model. 

My ollama instance does have some environment variables that enable remote serving.

[Service]
Environment="OLLAMA_HOST=0.0.0.0"
Environment="OLLAMA_ORIGINS=*"

![image](https://github.com/user-attachments/assets/9a0926cc-7ebd-4890-b4e7-259077755c27)
